ibm-watson-iot/functions

scripts/cerealfiller_entity_and_test_pipeline.py

[flake8](http://flake8.pycqa.org) testing of https://github.com/ibm-watson-iot/functions on Python 3.7.1
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./scripts/cerealfiller_entity_and_test_pipeline.py:88:7: F821 undefined name 'SimpleRegressor'
est = SimpleRegressor(features=['temp','humidity','fill_time'],targets=['fill_mass'])
^
1     F821 undefined name 'SimpleRegressor'
1
```

Undefined name: 'SimpleRegressor' called on line 88

---

iotfunctions/db.py

keyword 'text' was introduced with python 3.7 as an alias for 'universal_newlines'. We still run with python < 3.7. The current bug does not affect the pipeline because the pipeline uses the corresponding function defined in analytics_service_pipeline packages which is already fixed.

Change text -> universal_newlines to support python 3.6

---

iotfunctions/db.py

Query needs to quietly handle the cases where  the dimension table doesn't exist instead of exploding,
the dimension table isn't always guaranteed to be there by default

fix(db): tolerate the case where the dimension table might not yet exist

---

iotfunctions/base.py
iotfunctions/db.py

Enables [#644](https://github.ibm.com/wiotp/monitoring-dashboard/issues/644) by adding a flag in the catalog function registration indicating whether scope is enabled.
Scope is enabled by default (specified in BaseFunction), but can be overwritten when implementing a custom function. With this implementation, all functions (including Base and BIFs) will have scope enabled.

Added scope filter flag

---

iotfunctions/db.py

for this error - 
```python
Exception ignored in: <function Database.__del__ at 0x7fa7e88e7290>
Traceback (most recent call last):
File "/var/www/as-pipeline/iotfunctions/db.py", line 2810, in __del__
self.release_resource()
File "/var/www/as-pipeline/iotfunctions/db.py", line 2793, in release_resource
self.connection.dispose()
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2027, in dispose
self.pool = self.pool.recreate()
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 175, in recreate
dialect=self._dialect,
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 96, in __init__
Pool.__init__(self, creator, **kw)
File "<string>", line 2, in __init__
File …
```

ignored exception

---

.gitignore
iotfunctions/bif.py
iotfunctions/db.py
tests/unit/test_bif.py

Initialize standard/framework for unit testing.
Currently only have several functions in `bif.py` tested. Plan is to move on to testing `pipeline.py`, `metadata.py`, and `db.py` next, as this PR is just a starting point.
~~Also: as I was testing, I found and removed several lines of code that seemed to be unused in `bif.py`: 
`c = self._entity_type.get_attributes_dict()`.
If these are actually necessary for the functioning of the pipeline, then we can easily revert this. If we revert these deletions, we'll just need to mock them for the tests.~~

Initialize unit tests

---

iotfunctions/metadata.py

[patch] Handle missing hours/minutes in backtrack in metadata.py

---

iotfunctions/db.py

BTW, while I'm at it, on my partner's instance, the credential_as.json file downloaded from Monitor UI has incorrect COS credentials and incorrect keys for the PostgreSQL database...
https://ibm-ai-apps.slack.com/archives/CA60S5T88/p1605193611074900?thread_ts=1605192996.072900&cid=CA60S5T88

databaseName --> db for custom function creation usecase of postgres tenant.

---

iotfunctions/base.py

I have disabled old MergeActivity function "BaseDBActivityMerge" and renamed the new MergeActivity function "BaseDBActivityMerge2" to "BaseDBActivityMerge". 
We still need a link from "BaseDBActivityMerge2" to "BaseDBActivityMerge" because there is one entity type using it.

[patch] Disable old version of function BaseDBActivityMerge

---

iotfunctions/metadata.py

sklearn 0.22 and larger added an attribute to count the number of expected features and validates input data when called to transform or predict data using an sklearn model.
When an sklearn model built with older version is unpickled this attribute will be missing. The fix creates the missing attribute.
I installed sklearn 0.21.1, ran notebook MonitorAnomalyFunction to generate the scaling models
then installed sklearn 0.23.1, ran the notebook again to check and it turned out work
```
2021-02-03T17:49:39.977 INFO iotfunctions.dbtables.retrieve_model Model model.TEST_ENTITY_FOR_FFTBASEDGENERALIZEDANOMALYSCOREV2.FFTbasedGeneralizedAnomalyScoreV2.FFTAnomalyScore.MyRoom of size 1107 bytes has been retrieved from filesystem
2021-02-03T17:49:39.982 INFO iotfunctions.metadata.transform 0.20 !!! …
```

fix for sklearn scalers built with version < 0.22

---

iotfunctions/bif.py
requirements.txt

To perform an end-to-end testing in dev for issue https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/2470 we need to add ibm-watson-machine-learning to support InvokeWMLModel from this PR: https://github.com/ibm-watson-iot/functions/pull/408.
Will require new pipeline build before I can test in dev. @pkohlmann do we rebuild the base image manually after merging into dev?

[patch] missing library

---

iotfunctions/bif.py
tests/test_invoke_watson_studio.py

**Changes made in this PR**
1. Basic structure for testing the functionality of InvokeWatsonStudio. Since most of the fields are user defined we can currently only do local testing with this script
2. merged repetitive code to one block
For locally testing https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/2470

[patch] local testing support

---

iotfunctions/bif.py

When output_item is a str our function splits the name and creates unnecessary columns. Example below: MaxTemp is split into M, a, x, T, e, m, p, MaxTemp column. Currently, these columns should be deleted in persisted columns stage 
```
+----------------------------------------------------+-------+----------+--------+------------+-------------------+---------------------+--------------------+-----------+----------------------------+---------------------+------------+---------------------+---------------------+------------+-------------------------+---------------------+-----------------------------------+----------------------------+-----------------------+------------+-----------+--------------------+------------------+-----+-----+-----+-----+-----+-----+-----+-----------+
| …
```

[patch] handle case where output items is a string

---

iotfunctions/bif.py
tests/test_aggregate.py

Taking into account that state changes might be rare (less than one per run of StateTimePrep)
And taking into account that an aggregators operate on half-open intervals: 
For example, we get data from 23:55 or even closer, but 00:00 is out of reach. That doesn't matter for operations like max or mean, but it matters here.

fixed 3331

---

iotfunctions/db.py

Reverts ibm-watson-iot/functions#496

Revert "[patch] use internl core api during entity type creation"

---

requirements.txt

wiotp/Maximo-Asset-Monitor#5716
certifi is pulled in by requests, but the default version (certifi-2023.5.7) is vunerable to CVE-2023-37920
As 2.31.0 is the most recent version of requests, the version of certifi needs to be explicitly set to avoid this vulnerability

[patch] force version of certifi

---

iotfunctions/dbhelper.py
iotfunctions/dbtables.py
iotfunctions/loader.py
iotfunctions/stages.py

Refers to https://jsw.ibm.com/browse/MASMON-203

Kohlmann master sql injection

---

iotfunctions/aggregate.py

Refers to https://jsw.ibm.com/browse/MASMON-1067
Refers to https://jsw.ibm.com/browse/MASMON-1157

[patch] Office hours optional

---

iotfunctions/__init__.py
iotfunctions/aggregate.py
iotfunctions/anomaly.py
iotfunctions/bif.py
iotfunctions/dbhelper.py
iotfunctions/loader.py
iotfunctions/pipeline.py
iotfunctions/stages.py

Bump version to 9.0.3
Add RobustThreshold catalog function for space insights
Fix testcases (replaced deprecated parameter for scipy.signal.spectrogram)

9.0.x spaceinsights ai

---

iotfunctions/anomaly.py
iotfunctions/base.py
iotfunctions/bif.py
iotfunctions/experimental.py
iotfunctions/metadata.py
tests/test_base_estimator_function.py

Refers to https://jsw.ibm.com/browse/MASMON-1614

[patch] group_keys in groupby

---

requirements.txt

Refers to https://jsw.ibm.com/browse/MASMON-3550

[patch] downgrade scikit-learn to 1.3.0 for Predict

---

iotfunctions/metadata.py

Refers to https://jsw.ibm.com/browse/MASMON-3797

[patch] remove uuid for Predict II
