ibm-watson-iot/functions

iotfunctions/bif.py, iotfunctions/db.py, iotfunctions/metadata.py, iotfunctions/pipeline.py
Changes for new entity filter function and some performance related db work
=> Entity filter

iotfunctions/db.py
this is related to issue #1372 
Amritha and I just take the log output of the subprocess and paste it into our logger.
=> add log of subprocess to logfile

iotfunctions/db.py, iotfunctions/metadata.py, iotfunctions/pipeline.py, iotfunctions/util.py
This pull request is part of pull request #20 of analytics service pipeline. Pull request #20 requires this pull request to work properly because of the reference to class StageException
=> Kohl stages

iotfunctions/db.py
add feature to support passing the deviceid_col as a parameter to all the agg functions
Also a bug fix where the process_special_aggregates wasn't filtering on entities..
=> feat(db): deviceid_col as parameter

iotfunctions/db.py, iotfunctions/enginelog.py, iotfunctions/metadata.py, iotfunctions/pipeline.py, iotfunctions/util.py
=> Worked on #1688 to Object storage log files are not readable / inconsistent folder location/trace file folder structure change.

iotfunctions/metadata.py, iotfunctions/pipeline.py
* Removing redundant entity_type_name
* Null granularity issue.
=> Removing redundant entity_type_name and  fixing null granularity table names issue.

iotfunctions/bif.py
This reverts commit 883e06e2d1d8fb9b9aa52f083fd1b11e695215ce.
=> Revert "Adding new AlertTrueFalseValue function"

.gitignore, iotfunctions/db.py
bug where if no entities are passed, the derived metric time filters weren't being applied
=> fix(db): not filtering on filters if no entities passed

iotfunctions/metadata.py
Reverting back to the normal usecase. TODO: need to test entity data
generator. Which will create duplicate tables for the existing entity
types.
=> To overcome the sample entity type uppercase and lower case issue.

iotfunctions/anomaly.py, iotfunctions/base.py, scripts/train_estimator_model.py
python command to train a simple regressor model in scripts/train_estimator_model.py
=> training a simple regressor model

iotfunctions/bif.py
=> Issue#527 : Anomaly Generators

iotfunctions/bif.py, tests/test_anomaly_generators.py
Only works without any back tracking
=> issue855# Updated AnomalyGeneratorExtremeValue

iotfunctions/anomaly.py, tests/test_anomaly_functions.py
- Anomaly scoring on aggregate data
- Regression by entity (not across entities in entity-id), issue 895
- Regression with StandardScaler in Pipeline, issue 899
=> anomalies on aggregated data, regression per entity

iotfunctions/anomaly.py, iotfunctions/bif.py, iotfunctions/util.py, scripts/train_lightgbm_regressor.py
Hi,
I have slightly modified iotfunction/util.py so that traces are not saved to the database if trace_to_file is set. I bumped into issues with the training script otherwise and this was the modus operandi when traces were saved in ObjectStore.
=> updated training script

iotfunctions/base.py
=>  Minor function argument changes for locally testing aggregators

iotfunctions/db.py
https://github.ibm.com/wiotp/analytics-service/issues/2123
=> [patch] issue2123

iotfunctions/anomaly.py
As per discussion with Siva, I have made changes to only include **Expression Filter**.
=> [patch] issue#1023: Adding expression filter to Kmeans model

iotfunctions/db.py
https://github.ibm.com/wiotp/monitoring-dashboard/issues/1112
=> [patch] issue1112

iotfunctions/db.py
debug statements and outerjoin for every dimension join
=> [patch] issue1112 

iotfunctions/db.py, iotfunctions/dbtables.py, iotfunctions/stages.py
Pull request has a dependency to similiar pull request in analytics-service-pipeline.
issue #2203, #2197, #1991, #2208, #2209
=> Kohlmann grainid

iotfunctions/db.py
https://github.ibm.com/wiotp/monitoring-dashboard/issues/1170
=> [patch] issue1170

iotfunctions/pipeline.py
Needed to comment out the code that's affecting the merge performance.
Working on a different solution.
=> issue644# Performance issue with merge

iotfunctions/db.py
trying to fix the same problem mention in - https://github.com/ibm-watson-iot/functions/pull/238
=> ignored exception

iotfunctions/base.py, iotfunctions/bif.py
I have not registered the function yet because it is for Sandvik only and we have to think if we want to make it public to all.
=> New lookup function

iotfunctions/db.py
https://github.ibm.com/wiotp/analytics-service/issues/2221
https://github.ibm.com/IoT-Enterprise/analytics-service-library/pull/241
=> [patch] issue2221

iotfunctions/anomaly.py
Implement standard scaling for KMeans
=> Issue 739: Scale data prior to computing an anomaly score - KMeans only

iotfunctions/db.py
bug in forming query for filtering multiple dimensions values at once
=> [patch] bug in forming query for filtering dimensions

iotfunctions/anomaly.py
I added a set of new anomaly scorers with 'v2' appended to their names that "learn" and apply the proper scale of the input data before checking for anomalies
=> adding normalization, regrouped functions to increase readability

iotfunctions/util.py
for performance test logging of querydata (https://github.ibm.com/wiotp/monitoring-dashboard/issues/1387)
=> [patch] add process id in logs

iotfunctions/dbtables.py
Same change for KPI_DATA_CACHE as for KPI_MODEL_STORE
=> [patch] Switch ENTITY_TYPE_ID to BIGINT for KPI_DATA_CACHE

iotfunctions/anomaly.py, iotfunctions/base.py, iotfunctions/metadata.py
Support predictors that return mean and stddev.
Notebook to test:
https://github.com/sedgewickmm18/mmfunctions/blob/master/MonitorBayesianRegression.ipynb
based on 
https://github.com/sedgewickmm18/mmfunctions/blob/master/mmfunctions/anomaly.py
=> Support returning mean and stddev instead of a single valued predictor

scripts/sample_unroll_data.py, scripts/train_lightgbm_regressor.py
implemented as proposed in 1478
=> replace eval with ast.literal_eval

iotfunctions/base.py, iotfunctions/metadata.py, iotfunctions/pipeline.py
New version of MergeActivityDataSandvik
=> Kohlmann mergeactivity

iotfunctions/util.py
from Pipeline Controller code review:
https://github.ibm.com/IoT-Enterprise/analytics-service-pipeline/pull/196#discussion_r4129025
=> setuplogging accept filename

iotfunctions/db.py
https://github.ibm.com/wiotp/monitoring-dashboard/issues/1678
=> [patch] issue1678 closing query session

iotfunctions/db.py
(needed for new PipelineController)
1. moved PipelineController-Database to db-NativeDatabase
=> [patch] moving PipelineController db

setup.py
TODO: 
PR Liked with Issue: 
* https://github.ibm.com/wiotp/monitoring-dashboard/issues/1496
* https://github.ibm.com/wiotp/monitoring-dashboard/issues/1497
=> Upgrade urllib 1.24.3 to 1.26.2

iotfunctions/anomaly.py, setup.py
https://github.ibm.com/wiotp/monitoring-dashboard/issues/1673
Other PR for keeping packages cosistent
1. https://github.ibm.com/IoT-Enterprise/analytics-service-library/pull/334
2. https://github.ibm.com/IoT-Enterprise/analytics-service-pipeline/pull/204
=> issue1673 matrix profile

iotfunctions/anomaly.py
https://github.ibm.com/wiotp/monitoring-dashboard/issues/1673
=> issue 1673

iotfunctions/db.py
fix for cert issue seen here 
https://github.ibm.com/wiotp/monitoring-dashboard/issues/1690
Fix from : https://urllib3.readthedocs.io/en/latest/user-guide.html
=> [patch] issue1690

setup.py
Linked with https://github.ibm.com/wiotp/monitoring-dashboard/issues/1756
=> Upgrading Package version as per APM requirement.

iotfunctions/__init__.py, setup.py
Linked with issue wiotp/monitoring-dashboard#1777
=> Update pandas packages.

iotfunctions/db.py
https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/1770
=> [patch] make end_ts inclusive in where clause

iotfunctions/aggregate.py
please do not merge yet.
Support to execute aggregators outside of the pipeline - prereq to implement StateTime aggregator
=> Development support for aggregators

iotfunctions/db.py
https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/2189
=> [patch] error when splitting password

iotfunctions/db.py
to print the stack at point of faliure
=> add stack trace at point of faliure

iotfunctions/anomaly.py
https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/2212
=> [patch] matplotplib fails to load within lightgbm

iotfunctions/data_quality.py
improve function description and input parameter names to match documentation
also made changes in hook-db
relater PR in hook-db: https://github.ibm.com/IoT-Enterprise/hook-db-monitor/pull/127
for issue: https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/2340
=> [patch] improve function description and input parameter names

iotfunctions/bif.py
=> Implementation of InvokeWMLMethod

iotfunctions/bif.py
PR for bug
https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/2687
Tested with local testing
For issues
https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/2470
https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/2471
=> [patch] handling nans before calling watson studio

iotfunctions/db.py, iotfunctions/metadata.py
https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/2767
=> create sample entity v2 apis

iotfunctions/db.py, iotfunctions/metadata.py
https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/2857
=> Entity type creation

iotfunctions/db.py
=> [patch] core url issue

requirements.txt
Make sure the sqlachemy version on iotfunctions agrees with the pipeline version
=> Sqlalchemy parity with pipeline

iotfunctions/stages.py
I jst added line 349: "if kpi_func_dto is not None:"
=> Kohlmann super aggregator

iotfunctions/stages.py
Adds helpful logging about produced alerts back into the `dev` code.
=> re-adding alert logging

requirements.txt
=> chore(requirements.txt): update to wml version for CP4D 4.0.3

iotfunctions/bif.py, iotfunctions/entity.py, iotfunctions/metadata.py
**Git issue**
https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/3175
**Comment**
Dependent PR: https://github.ibm.com/wiotp/analytics-service-library/pull/509
**Testing**
Verified by creating all types of entities in AnalyticsServiceDev2
=> changes for create entity type logic

requirements.txt
Addresses security concern in lxml library.
=> [patch] update lxml to 4.6.5

iotfunctions/db.py, iotfunctions/metadata.py
https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/3446
=> [patch] for predict fail when creating entity

requirements.txt
Just updating the requirements to match our 8.6.1 fixpack
=> chore(merge): forward merge final fixes from master

iotfunctions/base.py, iotfunctions/db.py, requirements.txt
iotfunction was still on dill 0.3.0
=> [patch] push dill to version 0.3.2

iotfunctions/base.py
(cherry picked from commit 13109400cf997862ee8360410e6da903db35b33d)
=> [patch] start_date missing as column

iotfunctions/anomaly.py, tests/test_base_functions.py
Remove dropna prior to interpolate as it defeats the purpose of interpolating over NaNs.
=> Fix issue 5191

requirements.txt
wiotp/Maximo-Asset-Monitor#5716
=> [patch] force version of certifi

requirements.txt
moving numpy higher to avoid other versions being pulled in by the other packages
=> [patch] Update requirements.txt

iotfunctions/aggregate.py, iotfunctions/bif.py
refers to https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/5743
refers to https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/5742
=> Kohlmann master bugs

iotfunctions/bif.py
Refers to https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/5794
=> [patch] Do not invoke WML Model when empty DF

iotfunctions/loader.py
Refers to https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/5253
=> [patch] Allow schema in LoadTableAndConcat

requirements.txt
wiotp/Maximo-Asset-Monitor#5824
=> [patch] update urllib3

iotfunctions/stages.py
Refers to https://jsw.ibm.com/browse/MASMON-310
=> [patch] special characters like hyphen in dimension name

iotfunctions/loader.py
Refers to https://jsw.ibm.com/browse/MASMON-262
=> [patch] Include left boundary, exclude right boundary

requirements.txt
Refers to https://jsw.ibm.com/browse/MASMON-209
Refers to https://jsw.ibm.com/browse/MASMON-773
=> [patch] remove version inconsistency request/urllib II

iotfunctions/dbhelper.py, iotfunctions/dbtables.py, iotfunctions/loader.py, iotfunctions/stages.py
Refers to https://jsw.ibm.com/browse/MASMON-203
=> Kohlmann 8.10.x sql injection

iotfunctions/dbhelper.py, iotfunctions/dbtables.py, iotfunctions/loader.py, iotfunctions/stages.py
Refers to https://jsw.ibm.com/browse/MASMON-203
=> Kohlmann 8.11.x sql injection

iotfunctions/aggregate.py
Refers to https://jsw.ibm.com/browse/MASMON-1058
=> [patch] Make Count-function more stable

iotfunctions/bif.py
New out-of-box function to calculate occupancy rate in spaces.
=> [patch] - Occupancy Rate for Spaces

iotfunctions/aggregate.py, iotfunctions/util.py
Refers to https://jsw.ibm.com/browse/MASMON-1067
Refers to https://jsw.ibm.com/browse/MASMON-1157
=> [patch] Handle all devices + set negative counts to zero

iotfunctions/aggregate.py, iotfunctions/loader.py, iotfunctions/pipeline.py
Refers to https://jsw.ibm.com/browse/MASMON-1222
=> [patch] Timezones V

iotfunctions/aggregate.py, iotfunctions/bif.py
Refers to https://jsw.ibm.com/browse/MASMON-1067
Refers to https://jsw.ibm.com/browse/MASMON-1157
=> [patch] Occupancy by Unit with Boolean

.github/workflows/python-test.yml, .travis.yml, requirements.txt, tests/test_vi_anomaly.py
Refers to https://jsw.ibm.com/browse/MASMON-1390
Refers to https://jsw.ibm.com/browse/MASMON-1356
=> [patch] upgrade packages for CP4D 4.8

iotfunctions/util.py
Refers to https://jsw.ibm.com/browse/MASMON-1405
=> [patch] Enable weekly grain

iotfunctions/aggregate.py
Refers to https://jsw.ibm.com/browse/MASMON-1633
=> [patch] legacy support: allow unknown entities

iotfunctions/bif.py, iotfunctions/db.py, iotfunctions/metadata.py, iotfunctions/stages.py, iotfunctions/util.py
Refers to https://jsw.ibm.com/browse/MASMON-1724
=> Kohlmann 9.0.x summary function

iotfunctions/bif.py, iotfunctions/metadata.py, iotfunctions/pipeline.py, iotfunctions/stages.py
**Highlights**
- Add new data item type JSON
- Support database inserts on CLOB column
**Screenshot**
=> MASMON-1731 - Support to CLOB 

iotfunctions/dbhelper.py
Refers to https://jsw.ibm.com/browse/MASMON-2075
=> [patch] Allow dots in device name in sal injection check

iotfunctions/loader.py
Refers to https://jsw.ibm.com/browse/MASMON-2075
=> [patch] Allow dots in device name in sql injection check II

iotfunctions/dbhelper.py
Refers to https://jsw.ibm.com/browse/MASMON-2075
=> [patch] Allow dots in device name in sal injection check III

iotfunctions/dbhelper.py, iotfunctions/loader.py
Refers to https://jsw.ibm.com/browse/MASMON-2075
=> [patch] Allow dots in device name in sql injection check

iotfunctions/db.py
Refers to https://jsw.ibm.com/browse/MASMON-2191
=> [patch] execute children in parent pod

iotfunctions/dbhelper.py
Refers to https://jsw.ibm.com/browse/MASMON-2652
=> [patch] Allow period in data item names

iotfunctions/loader.py, iotfunctions/util.py
Refers to https://jsw.ibm.com/browse/MASMON-1419
=> [patch] Prevent log forging

requirements.txt
Refers to https://jsw.ibm.com/browse/MASMON-2827
=> [patch] downgrade scikit-learn frm 1.5.0 to 1.1.1

iotfunctions/metadata.py
Refers to https://jsw.ibm.com/browse/MASMON-2797
=> [patch] DM_WIOT_ENTITY_LIST ==> IOTANALYTICS.DEVICE_LIST

iotfunctions/metadata.py
Refers to https://jsw.ibm.com/browse/MASMON-2760
=> [patch] fix insertion of devices in DEVICE_LIST

iotfunctions/db.py, iotfunctions/metadata.py
Refers to https://jsw.ibm.com/browse/MASMON-3092
Refers to https://jsw.ibm.com/browse/MASMON-3093
=> [patch] fix generation of sample entity type

iotfunctions/anomaly.py, iotfunctions/db.py, iotfunctions/metadata.py, iotfunctions/sample.py
Refers to https://jsw.ibm.com/browse/MASMON-3092
=> [patch] fix generation of sample entity type II

iotfunctions/db.py, iotfunctions/stages.py
Refers to https://jsw.ibm.com/browse/MASMON-3130
Refers to https://jsw.ibm.com/browse/MASMON-3131
=> [patch] Remove DataDictionary from Pipeline

iotfunctions/base.py
Refers to https://jsw.ibm.com/browse/MASMON-3194
=> [patch] add group key to result df

iotfunctions/aggregate.py
Refers to https://jsw.ibm.com/browse/MASMON-3337
=> [patch] Make index available to aggregators

iotfunctions/aggregate.py
(cherry picked from commit fb54deacdb62cd3d4c1e26b6c19d5ae72598dbb9)
Refers to https://jsw.ibm.com/browse/MASMON-3337
=> [patch] Make index available for aggregators

iotfunctions/stages.py
Refers to https://jsw.ibm.com/browse/MASMON-3485
=> [patch] Avoid Null entries in DB2

iotfunctions/aggregate.py
Refers to https://jsw.ibm.com/browse/MASMON-3512
=> [patch] Cast types of empty dataframe in aggregation

iotfunctions/db.py, iotfunctions/metadata.py
Refers to https://jsw.ibm.com/browse/MASMON-3530
=> [patch] Sample Device Generation

iotfunctions/base.py
Refers to https://jsw.ibm.com/browse/MASMON-3087
=> [patch] getfullargspec

requirements.txt
Refers to https://jsw.ibm.com/browse/MASMON-3545
=> [patch] upgrade to transformers 4.48.0

requirements.txt
Ref: [MASMON-3742](https://jsw.ibm.com/browse/MASMON-3742)
=> [patch] Update lightGBM to 4.6.0 and transformers to 4.48.0

requirements.txt
8.11.x: update package transformers, lightGMB + fix check_sql_injection():
=> [patch] 8.11.x: update package transformers, lightGMB + fix check_sql_injection()

iotfunctions/metadata.py
Refers to https://jsw.ibm.com/browse/MASMON-3606
=> [patch] add eventName for sample entity types

iotfunctions/metadata.py
Refers to https://jsw.ibm.com/browse/MASMON-3606
=> [patch] event handling for sample entity types

iotfunctions/dbtables.py, iotfunctions/metadata.py
Refers to https://jsw.ibm.com/browse/MASMON-3797
=> [patch] remove uuid for Predict

iotfunctions/stages.py
Refers to https://jsw.ibm.com/browse/MASMON-3804
=> [patch] add DEVICE_UID to alert table

iotfunctions/metadata.py
(cherry picked from commit d25bfb90aa833e419cc3d1e4870688a03b5ebe51)
=> [patch] event handling for sample entity types + index=None

iotfunctions/metadata.py
https://jsw.ibm.com/browse/MASMON-3947
=> [patch] default_timestamp_utc

requirements.txt
https://jsw.ibm.com/browse/MASMON-3954
=> [patch] upgrade transformers to 4.51.3

iotfunctions/base.py, iotfunctions/bif.py, iotfunctions/loader.py, iotfunctions/ui.py
https://jsw.ibm.com/browse/MASMON-4010
=> [patch] switch schema retrieval to https

iotfunctions/db.py, iotfunctions/dbhelper.py, iotfunctions/dbtables.py, iotfunctions/loader.py, iotfunctions/metadata.py, iotfunctions/stages.py, requirements.txt
https://jsw.ibm.com/browse/MASMON-3816
=> [patch] Remove postgres

iotfunctions/db.py, iotfunctions/dbhelper.py, iotfunctions/dbtables.py, iotfunctions/loader.py, iotfunctions/metadata.py, iotfunctions/stages.py, requirements.txt
https://jsw.ibm.com/browse/MASMON-3817
=> https://jsw.ibm.com/browse/MASMON-3817

iotfunctions/base.py
https://jsw.ibm.com/browse/MASMON-4123
=> [patch] remove keep_tz from keyerror to fix timestamp

iotfunctions/aggregate.py, iotfunctions/pipeline.py
https://jsw.ibm.com/browse/MASMON-4096
=> [patch] Enable scope for NUMBER, BOOLEAN, TIMESTAMP and None

iotfunctions/db.py
(cherry picked from commit d545417f064a5be91d81815f1919d73108fa82b0)
=> [patch] fix self.commit() issue

requirements.txt
https://jsw.ibm.com/browse/MASMON-4662
=> [patch] Update urllib3 library as of security scan (MASMON-4662)
